export const lang = {
    current: 'pt',
    languages: [
        { code: 'pt', label: '🇧🇷 PT' },
        { code: 'en-uk', label: '🇬🇧 EN' },
        { code: 'es', label: '🇪🇸 ES' },
        { code: 'fr', label: '🇫🇷 FR' }
    ],
    db: {
        pt: {
            lang_label: "PTBR",
            lang_title: "Idioma",
            manifesto_title: "TΦT — Type over Tap",
            manifesto_subtitle: "Escrita privada em tempos de IA.",
            manifesto_body: "<div class=\"manifesto-top\"><h2>Este é um palco vazio.</h2><p>Você monta sua mesa. Depois escreve fora da rede.</p></div><div class=\"manifesto-lines\"><p>Você escreve localmente. Nada depende da internet. Nada se perde.</p><p>O celular guarda e transporta. Ideias viram notas.</p><p>Exportar e apagar fazem parte do ritual.</p></div><div class=\"manifesto-tech\"><p>O sistema registra o gesto humano: tempo, ritmo, sequência.</p><p>Sem conta. Sem nuvem. Sem telemetria.</p></div>",
            manifesto_accept: "LI E ENTENDI",
            manifesto_pomo_hint: "Escolha seu primeiro ciclo de trabalho.",
            terms_link: "Termos de uso",
            terms_accept_hint: "Ao iniciar uma sessão, você aceita os Termos de uso.",
            terms_title: "Uso responsável do TΦT",
            terms_body: "<p>O TΦT é uma ferramenta experimental criada por um escritor para ajudar outros escritores a trabalharem com mais privacidade e foco.</p><p>Ao usar este sistema, você entende e concorda que:</p><ul><li>O TΦT é fornecido \"como está\", sem garantias explícitas ou implícitas.</li><li>Falhas podem ocorrer, incluindo bugs, perda de dados, corrupção de arquivos, falhas do navegador, do dispositivo ou do sistema operacional, quedas de energia, travamentos, erros de uso ou limitações do ambiente local.</li><li>Embora o sistema tenha sido extensamente testado, nenhum software é infalível.</li><li>A responsabilidade por exportar, fazer backup, armazenar e proteger seus textos é exclusivamente do usuário.</li></ul><p>O TΦT não garante autoria legal, registro oficial, validade jurídica ou proteção absoluta de qualquer texto. Hashes, metadados e registros técnicos podem constituir evidência matemática de anterioridade, mas não substituem registros legais formais.</p><p>O autor do TΦT não se responsabiliza por perdas, danos diretos ou indiretos, lucros cessantes, interrupções, uso indevido do sistema, reivindicações de autoria ou expectativas não atendidas.</p><p>Ao aceitar estes termos, você reconhece que:</p><ul><li>está utilizando uma ferramenta independente,</li><li>criada como um experimento técnico e cultural,</li><li>sem suporte formal ou garantias de serviço,</li><li>e que assume total responsabilidade pela forma como a utiliza.</li></ul><p>Se você compreende e aceita estes termos, pode começar.</p>",
            terms_check: "Li, compreendi e aceito os termos de uso",
            terms_primary: "Aceitar e começar",
            terms_back: "Voltar",
            terms_tip: "Dica: exporte com frequência e guarde seus backups.",
            terms_close: "Fechar",
            verify_link: "Verificar arquivo .tot",
            welcome: "INICIALIZANDO SISTEMA",
            create_pass: "Crie a senha da sessão",
            repeat_pass: "CONFIRME A SENHA",
            setup_project_label: "Nome do projeto",
            start_btn: "CRIAR SESSÃO LOCAL",
            locked: "SISTEMA BLOQUEADO",
            unlock_btn: "DESBLOQUEAR",
            wrong_pass: "SENHA INCORRETA",
            reset_warn: "PERIGO: ISSO APAGARÁ TUDO. CONTINUAR?",
            reset_invalid: "SENHAS INVÁLIDAS OU DIVERGENTES.",
            reset_cancel: "SENHA INCORRETA. OPERAÇÃO CANCELADA.",
            reset_prompt: "DIGITE A SENHA DE ACESSO PARA CONFIRMAR O EXTERMÍNIO:",
            modal_title: "CONFIRMAÇÃO",
            modal_ok: "OK",
            modal_cancel: "CANCELAR",
            project_delete_confirm: "Apagar arquivo",
            stats_chars: "CHARS",
            stats_words: "WORDS",
            stats_label: "CHARS: 0 | WORDS: 0",
            marquee_ready: "/// SISTEMA PRONTO /// PRESSIONE [F1] PARA AJUDA :: DIGITE --H NO EDITOR",
            editor_placeholder: "Escreva aqui. Este texto nasce com autoria registrada.",
            font_title: "Ajustar leitura",
            font_mode_neutral: "Neutra",
            font_mode_literary: "Literária",
            font_mode_author: "Autor",
            font_minus_title: "Diminuir fonte",
            font_plus_title: "Aumentar fonte",
            save_title: "Salvar [Ctrl+S]",
            export_btn: "EXPORTAR",
            search_ph: "Buscar...",
            search_tip: "Buscar [Ctrl+F]",
            search_go: "IR",
            search_prev_title: "Anterior",
            search_next_title: "Próximo",
            paste_blocked: "Colagem não é permitida neste campo.\nPara colar conteúdo externo, use o Memo.",
            audio_title: "Som ambiente",
            audio_btn: "SOM",
            reader_title: "Ler sem editar",
            reader_btn: "LEITOR",
            reader_ruler_close_title: "Fechar régua",
            xray_title: "RASTRO",
            xray_btn: "RASTRO",
            verify_title: "TΦT Verify",
            verify_tip: "Verificar arquivo .tot",
            xray_tooltip: "Vestígios do processo de escrita",
            xray_locked_ptbr: "RASTRO é um modo desenvolvido em português do Brasil.\nOutras línguas aguardam adaptação.",
            xray_locked_intl: "RASTRO é um modo desenvolvido em português do Brasil.\nOutras línguas aguardam adaptação.",
            consult_title: "Consultar",
            consult_close_title: "Fechar",
            consult_button: "CONSULTAR",
            consult_pos: "Classe",
            consult_def: "Definição",
            consult_flex: "Flexões",
            consult_regency: "Regência",
            consult_examples: "Exemplos",
            consult_notes: "Observações",
            consult_doubt: "Dúvida comum",
            consult_not_found: "Palavra não encontrada no dicionário offline.",
            consult_amb_note: "Uso depende do contexto; leitura ambígua.",
            consult_out_scope: "Fora do escopo do dicionário offline (por enquanto).",
            consult_add_personal: "Aceitar como termo do autor",
            consult_status_idle: "—",
            consult_status_tried: "Tentativas:",
            consult_status_added: "Adicionada ao dicionário pessoal.",
            consult_class_unknown: "indeterminada (offline)",
            consult_class_probable: "provável",
            consult_class_context: "contexto",
            consult_fallback_title: "Observações no texto",
            consult_fallback_class: "Classe",
            consult_fallback_form: "Forma",
            consult_fallback_count: "Ocorrências no texto",
            consult_fallback_para: "Ocorrências no parágrafo",
            consult_fallback_repeat: "Repetição próxima",
            consult_fallback_singular: "Singular",
            consult_fallback_plural: "Plural",
            consult_fallback_yes: "Sim",
            consult_fallback_no: "Não",
            xray_panel_title: "RASTRO DO TEXTO",
            xray_help_title: "Ajuda",
            xray_help_tip: "Ajuda",
            xray_drag_title: "Mover",
            xray_drag_tip: "Arrastar janela",
            xray_close_title: "Fechar",
            xray_close_tip: "Fechar",
            xray_verbs_title: "VERBOS",
            xray_adjs_title: "ADJETIVOS",
            xray_tab_verbs: "Verbos",
            xray_tab_adjs: "Adjetivos",
            xray_tab_review: "Revisar",
            xray_tip_lex: "Léxico validado.",
            xray_tip_heur: "Heurística sem validação.",
            xray_tip_amb: "Forma ambígua (mais de uma leitura).",
            xray_tip_high: "Confiança alta (léxico).",
            xray_tip_med: "Confiança média (consenso parcial).",
            xray_tip_low: "Confiança baixa (heurística).",
            xray_tip_uncertain: "Lema incerto (sem validação).",
            xray_search_ph: "Buscar lema ou forma...",
            xray_sort_count: "Ocorrências",
            xray_sort_alpha: "A-Z",
            xray_sort_conf: "Confiança",
            xray_filter_amb_only: "Só ambíguos",
            xray_label_verbs: "Verbos",
            xray_label_adjs: "Adjetivos",
            xray_label_occurrences: "ocorrências",
            xray_label_lemmas: "lemas",
            xray_label_amb: "Ambíguos",
            xray_badge_verb: "VERBO",
            xray_badge_adj: "ADJ",
            xray_badge_alert: "ALERTA",
            xray_lemma_tooltip: "LEMA é a forma-base da palavra, usada para agrupar variações. Ex.: amo, amar, amarei → amar.",
            xray_lemma_unknown: "LEMA INDEFINIDO",
            xray_lemma_unknown_badge: "INCERTO",
            xray_part_reason_aux: "Auxiliar forte antes do particípio.",
            xray_part_reason_aux_weak: "Auxiliar de estado antes do particípio.",
            xray_part_reason_passive: "Possível voz passiva (por...).",
            xray_part_reason_intensifier: "Intensificador típico de adjetivo.",
            xray_part_reason_noun: "Após substantivo com determinante.",
            xray_part_reason_coord: "Coordenação com adjetivo.",
            xray_part_reason_amb: "Contexto insuficiente para decidir.",
            xray_part_alternatives: "Possíveis análises",
            xray_alert_tag: "ALERTA",
            xray_alert_doubt: "Duda",
            xray_alert_regency: "Régimen",
            xray_alert_style_adj: "Repetición de adjetivo",
            xray_alert_style_tense: "Verbos en el mismo tiempo",
            xray_alert_style_serestar: "Uso excesivo de ser/estar",
            xray_alert_paragraph: "párrafo",
            xray_alert_occurrences: "ocurrencias",
            xray_badge_alert: "ALERTA",
            xray_alert_tag: "ALERTA",
            xray_alert_doubt: "Dúvida",
            xray_alert_regency: "Regência",
            xray_alert_style_adj: "Repetição de adjetivo",
            xray_alert_style_tense: "Verbos no mesmo tempo",
            xray_alert_style_serestar: "Uso excessivo de ser/estar",
            xray_alert_paragraph: "parágrafo",
            xray_alert_occurrences: "ocorrências",
            xray_legend_lex: "LÉX",
            xray_legend_heur: "HEUR",
            xray_legend_amb: "AMB",
            xray_legend_high: "ALTA",
            xray_legend_med: "MÉDIA",
            xray_legend_low: "BAIXA",
            xray_help_heading: "Legenda",
            xray_help_body: "<p><strong>LEMA</strong> é a forma base (ex.: amar). <strong>FORMA</strong> é o que aparece no texto.</p><p><strong>TAG</strong> mostra forma/tempo: INF, GER, PART, PRES, FUT, IMP, COND.</p><p><strong>ALTA</strong> = léxico. <strong>MÉDIA</strong> = consenso parcial. <strong>BAIXA</strong> = heurística.</p><p><strong>AMB</strong> = forma ambígua (pode ser mais de uma classe).</p>",
            xray_empty: "Sem dados suficientes.",
            xray_policy: "Agrupa por lema. Conta verbos (inclui infinitivo/gerúndio/particípio) e adjetivos. Ambíguos aparecem marcados.",
            xray_lexicon_status: "Pacote linguístico",
            xray_audit_toggle: "Auditar",
            xray_conf_high: "alta",
            xray_conf_med: "média",
            xray_conf_low: "baixa",
            lock_title: "Proteger a sessão",
            lock_btn: "LOCK",
            export_title: "PROTOCOLO DE EXPORTAÇÃO",
            export_markdown: "EXPORTAR MARKDOWN",
            export_json: "EXPORTAR CÁPSULA",
            export_capsule_tip: "Arquivo verificável de escrita humana criado no TΦT.",
            export_report_full: "IMPRESSÃO COMPLETA",
            export_qr_stream: "STREAM QR",
            export_note: "Contém texto e prova técnica do processo de escrita.",
            export_social_title: "REDES FEDERADAS",
            export_social_bigtech: "REDES NÃO FEDERADAS (ONDE VOCÊ NÃO TEM CONTROLE SOBRE SEU CONTEÚDO)",
            share_title: "DIVULGAR TΦT",
            share_copy: "COPIAR TEXTO",
            share_open: "ABRIR REDE",
            share_message: "Eu escrevo no 🔸 TΦT Writer. Escreveu, exportou, apagou. Um bunker offline para escrever com privacidade. https://tot.undo.it/",
            fediverse_help: "NÃO SABE O QUE É O FEDIVERSO?",
            fediverse_title: "FEDIVERSO",
            fediverse_body: "<p>Pense em redes sociais como email: você pode usar qualquer provedor e falar com qualquer pessoa. O fediverso funciona assim.</p><p>Em vez de uma empresa mandar em tudo, várias comunidades se conectam. Você escolhe onde morar, leva seus dados e ainda conversa com todo mundo.</p><p>É menos vigilância, mais controle e mais liberdade.</p>",
            export_active: "ativo",
            export_all: "tudo",
            export_light: "luz",
            danger_zone: "ZONA DE PERIGO",
            reset_warn_body: "Isso apagará TODOS os arquivos e configurações.",
            reset_proof: "VERIFICAÇÃO DE CONTEÚDO: DIGITE UMA PALAVRA DO TEXTO",
            reset_keyword: "Palavra do texto",
            reset_validate: "Verificar conteúdo",
            reset_confirm: "SIM, QUERO APAGAR",
            reset_password_prompt: "Digite a senha da sessão para autorizar a destruição:",
            reset_password_ph: "Senha da sessão",
            reset_destroy: "Destruir sessão local",
            pomo_locked: "CICLO DE ESCRITA ATIVO",
            pomo_break: "PAUSA ATIVA",
            pomo_break_hint: "Desbloqueio exige a senha da sessão.",
            pomo_unlock_prompt: "DIGITE A SENHA DA SESSÃO PARA LIBERAR:",
            pomo_choice: "ESCOLHA O PRÓXIMO BLOCO:",
            pomo_25: "25 MIN",
            pomo_55: "50 MIN",
            pomo_btn: "POMODORO",
            pomo_tip: "Ciclo de foco",
            help_title: "MANUAL DE COMANDO",
            help_tab_general: "GERAL",
            help_tab_tools: "FERRAMENTAS",
            help_tab_nav: "ESTRUTURA",
            help_tab_slash: "SLASH COMMANDS",
            help_help: "Ajuda",
            help_save: "Salvar / Exportar",
            help_open: "Abrir / Importar",
            help_fullscreen: "Tela Cheia (Zen)",
            help_search: "Buscar",
            help_close: "Fechar / Focar Editor",
            help_theme: "Trocar Tema",
            help_music: "Música (Play / Stop)",
            help_pomo: "Ciclo de escrita",
            help_font: "Mudar Fonte",
            help_files: "Abrir Arquivos",
            help_nav: "Abrir Estrutura",
            help_memo: "Abrir Memos",
            help_drawer_close: "Fechar Gaveta",
            help_slash_hint: "Digite no editor para ativar:",
            help_save_short: "Salvar",
            help_open_short: "Importar",
            help_theme_short: "Mudar Tema",
            help_fullscreen_short: "Tela Cheia",
            help_music_short: "Música",
            help_pomo_short: "Ciclo de escrita",
            tab_files: "Transporte",
            tab_nav: "Estrutura e marcadores",
            tab_memo: "Anotar sem tocar no texto",
            tab_theme: "Ajustar o palco",
            tab_books: "Organizar ideias",
            hard_reset_title: "Apagar tudo localmente",
            fullscreen_title: "Tela Cheia [F11]",
            drawer_system: "SISTEMA",
            drawer_actions: "AÇÕES",
            drawer_search: "BUSCA",
            drawer_files: "ARQUIVOS",
            drawer_nav: "ESTRUTURA",
            drawer_memo: "MEMOS",
            btn_new_project: "+ NOVO",
            btn_import_title: "Importar JSON/TXT",
            btn_open: "ABRIR",
            btn_scan_qr: "Scan QR",
            btn_scan: "SCAN QR",
            nav_structure: "Estrutura do documento:",
            nav_insert: "INSERIR MARCADOR",
            nav_empty_hint: "Use \"Inserir Marcador\" para navegar.",
            nav_delete_confirm: "Apagar marcador",
            memo_ph: "Buffer de memória...",
            files_hint: "Controle seus arquivos e backups localmente.",
            nav_hint: "Veja a estrutura do documento e navegue pelos capítulos.",
            memo_hint: "Notas e trechos externos. Não gera autoria.",
            mobile_theme: "TROCAR TEMA",
            mobile_full_enable: "ATIVAR MODO COMPLETO",
            mobile_full_disable: "VOLTAR PARA MEMO",
            mobile_memo_ph: "Nota rápida...",
            mobile_memo_tags: "Tags (separe por vírgula)",
            mobile_memo_add: "SALVAR NOTA",
            mobile_memo_delete: "APAGAR",
            mobile_export_memos: "EXPORTAR MEMOS",
            mobile_intro_title: "MODO MOBILE",
            mobile_intro_body: "<p>Disponível offline após o primeiro acesso.</p><p>O mobile é reduzido ao essencial: scanner QR e notas rápidas.</p><p>Deslize para cima para esconder o scanner e escrever no memo.</p><p>Exporte JSON e importe no desktop para o projeto completo.</p>",
            mobile_intro_ok: "ENTENDI",
            offline_download: "BAIXAR APP OFFLINE",
            project_github: "GITHUB DO PROJETO",
            qr_stream_title: "STREAM QR",
            qr_stream_active: "STREAM ATIVO",
            qr_stream_pause: "PAUSAR",
            qr_stream_hint: "Feche para encerrar o envio.",
            qr_stream_instructions: "<p>1) No celular, abra o TΦT e vá em Arquivos → Scan QR.</p><p>2) Aponte para esta tela até completar.</p><p>3) Depois, apague tudo aqui.</p>",
            qr_scan_title: "SCAN QR",
            qr_scan_wait: "AGUARDANDO QR...",
            qr_scan_stop: "PARAR SCAN",
            qr_fallback_hint: "Sem câmera? Importe o arquivo .b64 ou cole a string.",
            qr_fallback_import: "IMPORTAR ARQUIVO",
            qr_fallback_paste: "Cole a string base64",
            qr_fallback_restore: "RESTAURAR",
            reader_glossary: "GLOSSÁRIO",
            lexicon_title: "DICIONARIO",
            lexicon_trans: "TRADUCOES",
            inline_data_title: "DADOS",
            inline_data_words: "Palavras",
            inline_data_chars: "Caracteres",
            inline_data_keys: "Toques",
            inline_data_cert: "Certidão",
            inline_data_session: "Sessão",
            inline_dice_title: "DADO",
            goal_label: "META",
            goal_done_title: "META CUMPRIDA",
            goal_done_body: "Parabéns, você atingiu sua meta de escrita.",
            goal_500_title: "500 PALAVRAS",
            goal_500_body: "Boa. Continue até 1000 palavras.",
            goal_1000_title: "1000 PALAVRAS",
            goal_1000_body: "Ótimo ritmo. Siga para 1500.",
            goal_1500_title: "1500 PALAVRAS",
            goal_1500_body: "Quase lá. Mire 2000.",
            goal_2000_title: "2000 PALAVRAS",
            goal_2000_body: "Excelente. Meta máxima atingida.",
            reader_glossary_title: "Glossário",
            reader_ruler_title: "Régua",
            reader_font_title: "Fonte",
            reader_theme_title: "Tema",
            reader_play_title: "Play",
            reader_close_title: "Fechar",
            default_project: "Rascunho Inicial",
            alert_backup_restored: "✅ BACKUP RESTAURADO COM SUCESSO!",
            alert_backup_invalid: "Erro: Backup inválido ou corrompido.",
            alert_capsule_restored: "✅ CÁPSULA TΦT RESTAURADA COM SUCESSO!",
            alert_capsule_invalid: "Erro: Cápsula inválida ou corrompida.",
            print_popup_blocked: "O navegador bloqueou a aba de impressão. Permita pop-ups para continuar.",
            alert_backup_json_error: "Erro ao ler arquivo JSON.",
            prompt_file_name: "Nome do Arquivo:",
            reset_no_text: "SEM TEXTO PARA VALIDAR. CONTINUE COM A ETAPA 2.",
            reset_proof_ok: "VERIFICAÇÃO OK.",
            reset_proof_fail: "PALAVRA INCORRETA.",
            reset_executing: "EXECUTANDO PROTOCOLO...",
            reset_denied: "SENHA INCORRETA. ACESSO NEGADO.",
            pomo_unlocked: "ACESSO LIBERADO.",
            pomo_wrong_pass: "SENHA INCORRETA.",
            pomo_break_label: "PAUSA",
            qr_stream_paused: "STREAM PAUSADO",
            qr_stream_resume: "RETOMAR",
            qr_stream_empty: "SEM DADOS PARA STREAM.",
            qr_libs_missing: "Pacote QR ainda não carregou. Tente novamente.",
            qr_no_detector: "BarcodeDetector indisponível. Use importação por arquivo.",
            qr_using_fallback: "Decoder offline ativo. Aponte a câmera.",
            qr_camera_missing: "Elemento de câmera ausente.",
            qr_camera_blocked: "CÂMERA BLOQUEADA OU INDISPONÍVEL.",
            qr_receiving: "RECEBENDO",
            qr_restore_in_progress: "BACKUP COMPLETO. RESTAURANDO...",
            qr_decode_fail: "FALHA NA DECODIFICAÇÃO."
            ,
            qr_frame: "FRAME"
            ,
            confirm_exit: "Deseja encerrar o sistema?"
            ,
            chapter_title: "NOVO CAPÍTULO",
            chapter_placeholder: "..."
        },
        "en-uk": {
            lang_label: "ENG",
            lang_title: "Language",
            manifesto_title: "TΦT — Type over Tap",
            manifesto_subtitle: "Private writing in times of AI.",
            manifesto_body: "<div class=\"manifesto-top\"><h2>This is an empty stage.</h2><p>You build your desk. Then you write off the network.</p></div><div class=\"manifesto-lines\"><p>You write locally. Nothing depends on the internet. Nothing is lost.</p><p>The phone stores and transports. Ideas become notes.</p><p>Exporting and deleting are part of the ritual.</p></div><div class=\"manifesto-tech\"><p>The system records the human gesture: time, rhythm, sequence.</p><p>No profiles. No cloud. No telemetry.</p></div>",
            manifesto_accept: "I HAVE READ AND UNDERSTOOD",
            manifesto_pomo_hint: "Choose your first work cycle.",
            terms_link: "Termos de uso",
            terms_accept_hint: "Ao iniciar uma sessão, você aceita os Termos de uso.",
            terms_title: "Responsible use of TΦT",
            terms_body: "<p>TΦT is an experimental tool created by a writer to help other writers work with more privacy and focus.</p><p>By using this system, you understand and agree that:</p><ul><li>TΦT is provided “as is”, without any express or implied warranties.</li><li>Failures may occur, including software bugs, data loss, file corruption, browser issues, device or operating system failures, power outages, crashes, misuse, or local environment limitations.</li><li>Although the system has been extensively tested, no software is infallible.</li><li>Responsibility for exporting, backing up, storing, and protecting your texts lies entirely with the user.</li></ul><p>TΦT does not guarantee legal authorship, official registration, legal validity, or absolute protection of any text. Hashes, metadata, and technical records may constitute mathematical evidence of prior existence, but they do not replace formal legal registration.</p><p>The author of TΦT assumes no liability for losses, direct or indirect damages, loss of profits, service interruptions, misuse of the system, authorship claims, or unmet expectations.</p><p>By accepting these terms, you acknowledge that:</p><ul><li>you are using an independent tool,</li><li>created as a technical and cultural experiment,</li><li>without formal support or service guarantees,</li><li>and that you assume full responsibility for how you use it.</li></ul><p>If you understand and accept these terms, you may begin.</p>",
            terms_check: "I have read, understood, and accept the terms of use",
            terms_primary: "Accept and start",
            terms_back: "Voltar",
            terms_tip: "Dica: exporte com frequência e guarde seus backups.",
            terms_close: "Fechar",
            verify_link: "Verify .tot file",
            welcome: "INITIALISING SYSTEM",
            create_pass: "CREATE SESSION PASSWORD",
            repeat_pass: "CONFIRM PASSWORD",
            setup_project_label: "Project name",
            start_btn: "CREATE LOCAL SESSION",
            locked: "SYSTEM LOCKED",
            unlock_btn: "UNLOCK",
            wrong_pass: "INCORRECT PASSWORD",
            reset_warn: "WARNING: THIS WILL WIPE EVERYTHING. PROCEED?",
            reset_invalid: "INVALID OR MISMATCHED PASSWORDS.",
            reset_cancel: "WRONG PASSWORD. OPERATION CANCELLED.",
            reset_prompt: "ENTER THE SESSION PASSWORD TO CONFIRM ERASURE:",
            modal_title: "CONFIRMATION",
            modal_ok: "OK",
            modal_cancel: "CANCEL",
            project_delete_confirm: "Delete file",
            stats_chars: "CHARS",
            stats_words: "WORDS",
            stats_label: "CHARS: 0 | WORDS: 0",
            marquee_ready: "/// SYSTEM READY /// PRESS [F1] FOR HELP :: TYPE --H IN THE EDITOR",
            editor_placeholder: "Write here. This text is born with registered authorship.",
            font_title: "Change Font [Alt+F]",
            font_mode_neutral: "Neutral",
            font_mode_literary: "Literary",
            font_mode_author: "Author",
            font_minus_title: "Decrease font",
            font_plus_title: "Increase font",
            save_title: "Save [Ctrl+S]",
            export_btn: "EXPORT",
            search_ph: "Search…",
            search_tip: "Search [Ctrl+F]",
            search_go: "GO",
            search_prev_title: "Previous",
            search_next_title: "Next",
            paste_blocked: "Pasting is not allowed in this field.\nUse Memo for external content.",
            search_clear_title: "Clear search",
            audio_title: "Music [Alt+M]",
            audio_btn: "SOUND",
            reader_title: "Reader Mode",
            reader_btn: "READER",
            reader_ruler_close_title: "Close ruler",
            xray_title: "RASTRO",
            xray_btn: "RASTRO",
            verify_title: "TΦT Verify",
            verify_tip: "Verify .tot file",
            xray_tooltip: "Disponível em português do Brasil",
            xray_locked_intl: "RASTRO is currently available only in Brazilian Portuguese.",
            consult_title: "Consult",
            consult_close_title: "Close",
            consult_button: "CONSULT",
            consult_pos: "Class",
            consult_def: "Definition",
            consult_flex: "Forms",
            consult_regency: "Regency",
            consult_examples: "Examples",
            consult_notes: "Notes",
            consult_doubt: "Common doubt",
            consult_not_found: "Word not found in the offline dictionary.",
            consult_amb_note: "Usage depends on context; ambiguous reading.",
            consult_out_scope: "Outside the offline dictionary scope (for now).",
            consult_add_personal: "Accept as author term",
            consult_status_idle: "—",
            consult_status_tried: "Tried:",
            consult_status_added: "Added to personal dictionary.",
            consult_class_unknown: "undetermined (offline)",
            consult_class_probable: "probable",
            consult_class_context: "context",
            consult_fallback_title: "Text observations",
            consult_fallback_class: "Class",
            consult_fallback_form: "Form",
            consult_fallback_count: "Occurrences in text",
            consult_fallback_para: "Occurrences in paragraph",
            consult_fallback_repeat: "Nearby repetition",
            consult_fallback_singular: "Singular",
            consult_fallback_plural: "Plural",
            consult_fallback_yes: "Yes",
            consult_fallback_no: "No",
            xray_panel_title: "TEXT X-RAY",
            xray_help_title: "Help",
            xray_help_tip: "Help",
            xray_drag_title: "Move",
            xray_drag_tip: "Drag window",
            xray_close_title: "Close",
            xray_close_tip: "Close",
            xray_verbs_title: "VERBS",
            xray_adjs_title: "ADJECTIVES",
            xray_tab_verbs: "Verbs",
            xray_tab_adjs: "Adjectives",
            xray_tab_review: "Review",
            xray_tip_lex: "Lexicon validated.",
            xray_tip_heur: "Heuristic without validation.",
            xray_tip_amb: "Ambiguous form (more than one reading).",
            xray_tip_high: "High confidence (lexicon).",
            xray_tip_med: "Medium confidence (partial consensus).",
            xray_tip_low: "Low confidence (heuristic).",
            xray_tip_uncertain: "Uncertain lemma (no validation).",
            xray_search_ph: "Search lemma or form...",
            xray_sort_count: "Occurrences",
            xray_sort_alpha: "A-Z",
            xray_sort_conf: "Confidence",
            xray_filter_amb_only: "Ambiguous only",
            xray_label_verbs: "Verbs",
            xray_label_adjs: "Adjectives",
            xray_label_occurrences: "occurrences",
            xray_label_lemmas: "lemmas",
            xray_label_amb: "Ambiguous",
            xray_badge_verb: "VERB",
            xray_badge_adj: "ADJ",
            xray_badge_alert: "ALERT",
            xray_lemma_tooltip: "LEMMA is the base form used to group variations. Example: love, to love, loved → love.",
            xray_lemma_unknown: "LEMMA UNCERTAIN",
            xray_lemma_unknown_badge: "UNCERTAIN",
            xray_part_reason_aux: "Strong auxiliary before the participle.",
            xray_part_reason_aux_weak: "State auxiliary before the participle.",
            xray_part_reason_passive: "Possible passive voice (by...).",
            xray_part_reason_intensifier: "Typical adjective intensifier.",
            xray_part_reason_noun: "After noun with determiner.",
            xray_part_reason_coord: "Coordinated with an adjective.",
            xray_part_reason_amb: "Context not enough to decide.",
            xray_part_alternatives: "Possible analyses",
            xray_alert_tag: "ALERT",
            xray_alert_doubt: "Common doubt",
            xray_alert_regency: "Regency",
            xray_alert_style_adj: "Adjective repetition",
            xray_alert_style_tense: "Same tense verbs",
            xray_alert_style_serestar: "Excessive use of ser/estar",
            xray_alert_paragraph: "paragraph",
            xray_alert_occurrences: "occurrences",
            xray_legend_lex: "LEX",
            xray_legend_heur: "HEUR",
            xray_legend_amb: "AMB",
            xray_legend_high: "HIGH",
            xray_legend_med: "MED",
            xray_legend_low: "LOW",
            xray_help_heading: "Legend",
            xray_help_body: "<p><strong>LEMMA</strong> is the base form (e.g., to love). <strong>FORM</strong> is what appears in the text.</p><p><strong>TAG</strong> shows form/tense: INF, GER, PART, PRES, FUT, IMP, COND.</p><p><strong>HIGH</strong> = lexicon. <strong>MED</strong> = partial consensus. <strong>LOW</strong> = heuristic.</p><p><strong>AMB</strong> = ambiguous form (more than one class).</p>",
            xray_empty: "Not enough data.",
            xray_policy: "Grouped by lemma. Counts verbs (including infinitive/gerund/participle) and adjectives. Ambiguous items are marked.",
            xray_lexicon_status: "Language pack",
            xray_audit_toggle: "Audit mode",
            xray_conf_high: "high",
            xray_conf_med: "medium",
            xray_conf_low: "low",
            lock_title: "Lock Screen [Alt+L]",
            lock_btn: "LOCK",
            export_title: "EXPORT PROTOCOL",
            export_markdown: "EXPORT MARKDOWN",
            export_json: "EXPORT CAPSULE",
            export_capsule_tip: "A verifiable file of human writing created in TΦT.",
            export_report_full: "FULL EXPORT",
            export_qr_stream: "QR STREAM",
            export_note: "Contains the text and technical proof of the writing process.",
            export_social_title: "FEDERATED NETWORKS",
            export_social_bigtech: "NON-FEDERATED NETWORKS (LESS CONTROL)",
            share_title: "SHARE TΦT",
            share_copy: "COPY TEXT",
            share_open: "OPEN NETWORK",
            share_message: "I write in 🔸 TΦT Writer — an offline writing tool. Written, exported, erased. A private space for writing. https://tot.undo.it/",
            fediverse_help: "DON'T KNOW WHAT THE FEDIVERSE IS?",
            fediverse_title: "FEDIVERSE",
            fediverse_body: "<p>Think of social networks like email: you choose a provider and still talk to everyone.</p><p>The fediverse works the same way. Independent communities connected by open protocols.</p><p>Less surveillance. More control. More freedom.</p>",
            export_active: "active",
            export_all: "all",
            export_light: "light",
            danger_zone: "DANGER ZONE",
            reset_warn_body: "This will delete ALL local files and settings.",
            reset_proof: "CONTENT VERIFICATION: TYPE A WORD FROM THE TEXT",
            reset_keyword: "Word from text",
            reset_validate: "Verify content",
            reset_confirm: "DELETE LOCAL DATA",
            reset_password_prompt: "ENTER THE SESSION PASSWORD TO AUTHORISE DESTRUCTION:",
            reset_password_ph: "Session password",
            reset_destroy: "DESTROY LOCAL SESSION",
            pomo_locked: "WRITING CYCLE ACTIVE",
            pomo_break: "BREAK ACTIVE",
            pomo_break_hint: "Unlocking requires the session password.",
            pomo_unlock_prompt: "ENTER SESSION PASSWORD TO UNLOCK:",
            pomo_choice: "CHOOSE THE NEXT BLOCK:",
            pomo_25: "25 MIN",
            pomo_55: "50 MIN",
            pomo_btn: "POMODORO",
            pomo_tip: "Writing cycle",
            help_title: "COMMAND MANUAL",
            help_tab_general: "GENERAL",
            help_tab_tools: "TOOLS",
            help_tab_nav: "STRUCTURE",
            help_tab_slash: "SLASH COMMANDS",
            help_help: "Help",
            help_save: "Save / Export",
            help_open: "Open / Import",
            help_fullscreen: "Full Screen (Zen)",
            help_search: "Search",
            help_close: "Close / Focus Editor",
            help_theme: "Change Theme",
            help_music: "Music (Play / Stop)",
            help_pomo: "Writing Cycle",
            help_font: "Change Font",
            help_files: "Open Files",
            help_nav: "Open Structure",
            help_memo: "Open Memos",
            help_drawer_close: "Close Drawer",
            help_slash_hint: "Type in editor to trigger:",
            help_save_short: "Save",
            help_open_short: "Import",
            help_theme_short: "Change Theme",
            help_fullscreen_short: "Full Screen",
            help_music_short: "Music",
            help_pomo_short: "Writing Cycle",
            tab_files: "Files [Alt+1]",
            tab_nav: "Structure [Alt+2]",
            tab_memo: "Memos [Alt+3]",
            tab_theme: "Theme [Alt+T]",
            tab_books: "TΦTBooks [Alt+4]",
            hard_reset_title: "HARD RESET",
            fullscreen_title: "Fullscreen [F11]",
            drawer_system: "SYSTEM",
            drawer_actions: "ACTIONS",
            drawer_search: "SEARCH",
            drawer_files: "FILES",
            drawer_nav: "STRUCTURE",
            drawer_memo: "MEMOS",
            btn_new_project: "+ NEW",
            btn_import_title: "Import JSON/TXT",
            btn_open: "OPEN",
            btn_scan_qr: "Scan QR",
            btn_scan: "SCAN QR",
            nav_structure: "Document structure:",
            nav_insert: "INSERT MARKER",
            nav_empty_hint: "Use \"Insert marker\" to navigate.",
            nav_delete_confirm: "Delete marker",
            memo_ph: "Quick note…",
            files_hint: "Control your files and local backups.",
            nav_hint: "See the document structure and navigate markers.",
            memo_hint: "External notes and excerpts. No authorship record.",
            mobile_theme: "CHANGE THEME",
            mobile_full_enable: "ENABLE FULL MODE",
            mobile_full_disable: "BACK TO MEMO",
            mobile_memo_ph: "Quick note…",
            mobile_memo_tags: "Tags (comma separated)",
            mobile_memo_add: "SAVE MEMO",
            mobile_memo_delete: "DELETE",
            mobile_export_memos: "EXPORT MEMOS",
            mobile_intro_title: "MOBILE MODE",
            mobile_intro_body: "<p>Available offline after the first access.</p><p>Mobile is reduced to the essentials: QR scanner and quick notes.</p><p>Swipe up to hide the scanner and write memos.</p><p>Export JSON and import it on desktop for the full project.</p>",
            mobile_intro_ok: "UNDERSTOOD",
            offline_download: "DOWNLOAD OFFLINE APP",
            project_github: "PROJECT GITHUB",
            qr_stream_title: "QR STREAM",
            qr_stream_active: "STREAM ACTIVE",
            qr_stream_pause: "PAUSE",
            qr_stream_hint: "Close to end the stream.",
            qr_stream_instructions: "<p>1) On your phone, open TΦT and go to Files → Scan QR.</p><p>2) Point to this screen until it completes.</p><p>3) Then wipe everything here.</p>",
            qr_scan_title: "SCAN QR",
            qr_scan_wait: "WAITING FOR QR...",
            qr_scan_stop: "STOP SCAN",
            qr_fallback_hint: "No camera? Import the .b64 file or paste the string.",
            qr_fallback_import: "IMPORT FILE",
            qr_fallback_paste: "Paste the base64 string",
            qr_fallback_restore: "RESTORE",
            reader_glossary: "GLOSSARY",
            lexicon_title: "DICTIONARY",
            lexicon_trans: "TRANSLATIONS",
            inline_data_title: "DATA",
            inline_data_words: "Words",
            inline_data_chars: "Characters",
            inline_data_keys: "Keystrokes",
            inline_data_cert: "Certificate",
            inline_data_session: "Session",
            inline_dice_title: "DICE",
            goal_label: "GOAL",
            goal_done_title: "GOAL COMPLETE",
            goal_done_body: "Congrats, you reached your writing goal.",
            goal_500_title: "500 WORDS",
            goal_500_body: "Good. Keep going to 1000 words.",
            goal_1000_title: "1000 WORDS",
            goal_1000_body: "Great pace. Push for 1500.",
            goal_1500_title: "1500 WORDS",
            goal_1500_body: "Almost there. Aim for 2000.",
            goal_2000_title: "2000 WORDS",
            goal_2000_body: "Excellent. Max goal reached.",
            reader_glossary_title: "Glossary",
            reader_ruler_title: "Ruler",
            reader_font_title: "Font",
            reader_theme_title: "Theme",
            reader_play_title: "Play",
            reader_close_title: "Close",
            default_project: "Initial Draft",
            alert_backup_restored: "✅ BACKUP RESTORED SUCCESSFULLY",
            alert_backup_invalid: "Error: Invalid or corrupted backup.",
            alert_capsule_restored: "✅ TΦT CAPSULE RESTORED SUCCESSFULLY",
            alert_capsule_invalid: "Error: Invalid capsule.",
            print_popup_blocked: "Your browser blocked the print tab. Allow pop-ups to continue.",
            alert_backup_json_error: "Error reading JSON file.",
            prompt_file_name: "File Name:",
            reset_no_text: "NO TEXT TO VERIFY. CONTINUE TO THE NEXT STEP.",
            reset_proof_ok: "VERIFICATION ACCEPTED.",
            reset_proof_fail: "WORD NOT FOUND.",
            reset_executing: "EXECUTING PROTOCOL…",
            reset_denied: "INCORRECT PASSWORD. ACCESS DENIED.",
            pomo_unlocked: "ACCESS GRANTED",
            pomo_wrong_pass: "INCORRECT PASSWORD",
            pomo_break_label: "BREAK",
            qr_stream_paused: "STREAM PAUSED",
            qr_stream_resume: "RESUME",
            qr_stream_empty: "NO DATA TO STREAM.",
            qr_libs_missing: "QR pack not loaded yet. Try again.",
            qr_no_detector: "BarcodeDetector unavailable. Use file import.",
            qr_using_fallback: "Offline decoder active. Point the camera.",
            qr_camera_missing: "Camera element missing.",
            qr_camera_blocked: "CAMERA BLOCKED OR UNAVAILABLE.",
            qr_receiving: "RECEIVING",
            qr_restore_in_progress: "BACKUP COMPLETE. RESTORING...",
            qr_decode_fail: "DECODE FAILED."
            ,
            qr_frame: "FRAME"
            ,
            confirm_exit: "Do you want to close the system?"
            ,
            chapter_title: "NEW CHAPTER",
            chapter_placeholder: "..."
        },
        es: {
            lang_label: "ESP",
            lang_title: "Idioma",
            manifesto_title: "TΦT — Type over Tap",
            manifesto_subtitle: "Escritura privada en tiempos de IA.",
            manifesto_body: "<div class=\"manifesto-top\"><h2>Este es un escenario vacío.</h2><p>Usted monta su mesa. Luego escribe fuera de la red.</p></div><div class=\"manifesto-lines\"><p>Usted escribe localmente. Nada depende de internet. Nada se pierde.</p><p>El móvil guarda y transporta. Ideas se vuelven notas.</p><p>Exportar y borrar forman parte del ritual.</p></div><div class=\"manifesto-tech\"><p>El sistema registra el gesto humano: tiempo, ritmo, secuencia.</p><p>Sin perfiles. Sin nube. Sin telemetría.</p></div>",
            manifesto_accept: "LEÍ Y ENTENDÍ",
            manifesto_pomo_hint: "Elija su primer ciclo de trabajo.",
            terms_link: "Termos de uso",
            terms_accept_hint: "Ao iniciar uma sessão, você aceita os Termos de uso.",
            terms_title: "Uso responsable de TΦT",
            terms_body: "<p>TΦT es una herramienta experimental creada por un escritor para ayudar a otros escritores a trabajar con mayor privacidad y concentración.</p><p>Al utilizar este sistema, usted entiende y acepta que:</p><ul><li>TΦT se proporciona “tal como está”, sin garantías explícitas ni implícitas.</li><li>Pueden ocurrir fallos, incluidos errores de software, pérdida de datos, corrupción de archivos, fallos del navegador, del dispositivo o del sistema operativo, cortes de energía, bloqueos, uso incorrecto o limitaciones del entorno local.</li><li>Aunque el sistema ha sido ampliamente probado, ningún software es infalible.</li><li>La responsabilidad de exportar, hacer copias de seguridad, almacenar y proteger sus textos es exclusivamente del usuario.</li></ul><p>TΦT no garantiza autoría legal, registro oficial, validez jurídica ni protección absoluta de ningún texto. Los hashes, metadatos y registros técnicos pueden constituir evidencia matemática de existencia previa, pero no sustituyen registros legales formales.</p><p>El autor de TΦT no asume responsabilidad alguna por pérdidas, daños directos o indirectos, lucro cesante, interrupciones del servicio, uso indebido del sistema, reclamaciones de autoría o expectativas no cumplidas.</p><p>Al aceptar estos términos, usted reconoce que:</p><ul><li>está utilizando una herramienta independiente,</li><li>creada como un experimento técnico y cultural,</li><li>sin soporte formal ni garantías de servicio,</li><li>y que asume plena responsabilidad por el uso que haga de ella.</li></ul><p>Si comprende y acepta estos términos, puede comenzar.</p>",
            terms_check: "He leído, comprendido y acepto los términos de uso",
            terms_primary: "Aceptar y comenzar",
            terms_back: "Voltar",
            terms_tip: "Dica: exporte com frequência e guarde seus backups.",
            terms_close: "Fechar",
            verify_link: "Verificar archivo .tot",
            welcome: "INICIANDO SISTEMA",
            create_pass: "Crear contraseña de sesión",
            repeat_pass: "CONFIRMAR CONTRASEÑA",
            setup_project_label: "Nombre del proyecto",
            start_btn: "Crear sesión local",
            locked: "SISTEMA BLOQUEADO",
            unlock_btn: "DESBLOQUEAR",
            wrong_pass: "CONTRASEÑA INCORRECTA",
            reset_warn: "PELIGRO: ESTO BORRARÁ TODO. ¿SEGUIR?",
            reset_invalid: "CONTRASEÑAS INVÁLIDAS O DIFERENTES.",
            reset_cancel: "CONTRASEÑA INCORRECTA. OPERACIÓN CANCELADA.",
            reset_prompt: "INGRESE LA CONTRASEÑA PARA CONFIRMAR EL BORRADO:",
            modal_title: "CONFIRMACIÓN",
            modal_ok: "OK",
            modal_cancel: "CANCELAR",
            project_delete_confirm: "Borrar archivo",
            stats_chars: "CHARS",
            stats_words: "WORDS",
            stats_label: "CHARS: 0 | WORDS: 0",
            marquee_ready: "/// SISTEMA LISTO /// PRESIONE [F1] PARA AYUDA :: ESCRIBA --H EN EL EDITOR",
            editor_placeholder: "Escribe aquí. Este texto nace con autoría registrada.",
            font_title: "Cambiar Fuente [Alt+F]",
            font_mode_neutral: "Neutra",
            font_mode_literary: "Literaria",
            font_mode_author: "Autor",
            font_minus_title: "Disminuir fuente",
            font_plus_title: "Aumentar fuente",
            save_title: "Guardar [Ctrl+S]",
            export_btn: "EXPORTAR",
            search_ph: "Buscar...",
            search_tip: "Buscar [Ctrl+F]",
            search_go: "IR",
            search_prev_title: "Anterior",
            search_next_title: "Siguiente",
            paste_blocked: "Pegar no está permitido en este campo.\nUsa Memo para contenido externo.",
            search_clear_title: "Limpiar búsqueda",
            audio_title: "Música [Alt+M]",
            audio_btn: "SONIDO",
            reader_title: "Modo Lector",
            reader_btn: "LECTOR",
            reader_ruler_close_title: "Cerrar regla",
            xray_title: "RASTRO",
            xray_btn: "RASTRO",
            verify_title: "TΦT Verify",
            verify_tip: "Verificar archivo .tot",
            xray_tooltip: "Disponível em português do Brasil",
            xray_locked_intl: "RASTRO está disponible solo en portugués de Brasil por ahora.",
            consult_title: "Consultar",
            consult_close_title: "Cerrar",
            consult_button: "CONSULTAR",
            consult_pos: "Clase",
            consult_def: "Definición",
            consult_flex: "Flexiones",
            consult_regency: "Régimen",
            consult_examples: "Ejemplos",
            consult_notes: "Observaciones",
            consult_doubt: "Duda común",
            consult_not_found: "Palabra no encontrada en el diccionario offline.",
            consult_amb_note: "El uso depende del contexto; lectura ambigua.",
            consult_out_scope: "Fuera del alcance del diccionario offline (por ahora).",
            consult_add_personal: "Aceptar como término del autor",
            consult_status_idle: "—",
            consult_status_tried: "Intentos:",
            consult_status_added: "Agregada al diccionario personal.",
            consult_class_unknown: "indeterminada (offline)",
            consult_class_probable: "probable",
            consult_class_context: "contexto",
            consult_fallback_title: "Observaciones en el texto",
            consult_fallback_class: "Clase",
            consult_fallback_form: "Forma",
            consult_fallback_count: "Ocurrencias en el texto",
            consult_fallback_para: "Ocurrencias en el párrafo",
            consult_fallback_repeat: "Repetición cercana",
            consult_fallback_singular: "Singular",
            consult_fallback_plural: "Plural",
            consult_fallback_yes: "Sí",
            consult_fallback_no: "No",
            xray_panel_title: "RAYOS-X DEL TEXTO",
            xray_help_title: "Ayuda",
            xray_help_tip: "Ayuda",
            xray_drag_title: "Mover",
            xray_drag_tip: "Arrastrar ventana",
            xray_close_title: "Cerrar",
            xray_close_tip: "Cerrar",
            xray_verbs_title: "VERBOS",
            xray_adjs_title: "ADJETIVOS",
            xray_tab_verbs: "Verbos",
            xray_tab_adjs: "Adjetivos",
            xray_tab_review: "Revisar",
            xray_tip_lex: "Léxico validado.",
            xray_tip_heur: "Heurística sin validación.",
            xray_tip_amb: "Forma ambigua (más de una lectura).",
            xray_tip_high: "Confianza alta (léxico).",
            xray_tip_med: "Confianza media (consenso parcial).",
            xray_tip_low: "Confianza baja (heurística).",
            xray_tip_uncertain: "Lema incierto (sin validación).",
            xray_search_ph: "Buscar lema o forma...",
            xray_sort_count: "Ocurrencias",
            xray_sort_alpha: "A-Z",
            xray_sort_conf: "Confianza",
            xray_filter_amb_only: "Solo ambiguos",
            xray_label_verbs: "Verbos",
            xray_label_adjs: "Adjetivos",
            xray_label_occurrences: "ocurrencias",
            xray_label_lemmas: "lemas",
            xray_label_amb: "Ambiguos",
            xray_badge_verb: "VERBO",
            xray_badge_adj: "ADJ",
            xray_badge_alert: "ALERTA",
            xray_lemma_tooltip: "LEMA es la forma base usada para agrupar variaciones. Ej.: amo, amar, amarei → amar.",
            xray_lemma_unknown: "LEMA INDEFINIDO",
            xray_lemma_unknown_badge: "INCIERTO",
            xray_part_reason_aux: "Auxiliar fuerte antes del participio.",
            xray_part_reason_aux_weak: "Auxiliar de estado antes del participio.",
            xray_part_reason_passive: "Posible voz pasiva (por...).",
            xray_part_reason_intensifier: "Intensificador típico de adjetivo.",
            xray_part_reason_noun: "Después de sustantivo con determinante.",
            xray_part_reason_coord: "Coordinado con adjetivo.",
            xray_part_reason_amb: "Contexto insuficiente para decidir.",
            xray_part_alternatives: "Posibles análisis",
            xray_legend_lex: "LÉX",
            xray_legend_heur: "HEUR",
            xray_legend_amb: "AMB",
            xray_legend_high: "ALTA",
            xray_legend_med: "MEDIA",
            xray_legend_low: "BAJA",
            xray_help_heading: "Leyenda",
            xray_help_body: "<p><strong>LEMA</strong> es la forma base (ej.: amar). <strong>FORMA</strong> es lo que aparece en el texto.</p><p><strong>TAG</strong> muestra forma/tiempo: INF, GER, PART, PRES, FUT, IMP, COND.</p><p><strong>ALTA</strong> = léxico. <strong>MEDIA</strong> = consenso parcial. <strong>BAJA</strong> = heurística.</p><p><strong>AMB</strong> = forma ambigua (más de una clase).</p>",
            xray_empty: "Sin datos suficientes.",
            xray_policy: "Agrupa por lema. Cuenta verbos (incluye infinitivo/gerundio/participio) y adjetivos. Los elementos ambiguos aparecen marcados.",
            xray_lexicon_status: "Paquete lingüístico",
            xray_audit_toggle: "Auditar",
            xray_conf_high: "alta",
            xray_conf_med: "media",
            xray_conf_low: "baja",
            lock_title: "Bloquear Pantalla [Alt+L]",
            lock_btn: "LOCK",
            export_title: "PROTOCOLO DE EXPORTACIÓN",
            export_markdown: "EXPORTAR MARKDOWN",
            export_json: "EXPORTAR CÁPSULA",
            export_capsule_tip: "Archivo verificable de escritura humana creado en TΦT.",
            export_report_full: "IMPRESIÓN COMPLETA",
            export_qr_stream: "STREAM QR",
            export_note: "Contiene texto y prueba técnica del proceso de escritura.",
            export_social_title: "REDES FEDERADAS",
            export_social_bigtech: "REDES NO FEDERADAS (SIN CONTROL REAL SOBRE TU CONTENIDO)",
            share_title: "COMPARTIR TΦT",
            share_copy: "COPIAR TEXTO",
            share_open: "ABRIR RED",
            share_message: "Yo escribo en 🔸 TΦT Writer. Escribió, exportó, borró. Un bunker offline para escribir con privacidad. https://tot.undo.it/",
            fediverse_help: "NO SABES QUÉ ES EL FEDIVERSO?",
            fediverse_title: "FEDIVERSO",
            fediverse_body: "<p>Piensa en redes sociales como email: puedes elegir proveedor y hablar con cualquiera. El fediverso funciona igual.</p><p>En lugar de una empresa mandando todo, muchas comunidades se conectan. Tú eliges dónde estar, mantienes tus datos y sigues conectado.</p><p>Menos vigilancia, más control, más libertad.</p>",
            export_active: "activo",
            export_all: "todo",
            export_light: "luz",
            danger_zone: "ZONA DE PELIGRO",
            reset_warn_body: "Esto borrará TODOS los archivos y ajustes.",
            reset_proof: "VERIFICACIÓN DE CONTENIDO: ESCRIBA UNA PALABRA DEL TEXTO",
            reset_keyword: "Palabra del texto",
            reset_validate: "Verificar contenido",
            reset_confirm: "SÍ, BORRAR",
            reset_password_prompt: "INGRESE LA CONTRASEÑA DE SESIÓN PARA AUTORIZAR LA DESTRUCCIÓN:",
            reset_password_ph: "Contraseña de sesión",
            reset_destroy: "Destruir sesión local",
            pomo_locked: "CICLO DE ESCRITA ATIVO",
            pomo_break: "PAUSA ACTIVA",
            pomo_break_hint: "El desbloqueo requiere la contraseña de sesión.",
            pomo_unlock_prompt: "INGRESE LA CONTRASEÑA DE SESIÓN PARA DESBLOQUEAR:",
            pomo_choice: "ELIGE EL PRÓXIMO BLOQUE:",
            pomo_25: "25 MIN",
            pomo_55: "50 MIN",
            pomo_btn: "POMODORO",
            pomo_tip: "Ciclo de foco",
            help_title: "MANUAL DE COMANDOS",
            help_tab_general: "GENERAL",
            help_tab_tools: "HERRAMIENTAS",
            help_tab_nav: "ESTRUCTURA",
            help_tab_slash: "SLASH COMMANDS",
            help_help: "Ayuda",
            help_save: "Guardar / Exportar",
            help_open: "Abrir / Importar",
            help_fullscreen: "Pantalla Completa (Zen)",
            help_search: "Buscar",
            help_close: "Cerrar / Enfocar Editor",
            help_theme: "Cambiar Tema",
            help_music: "Música (Play / Stop)",
            help_pomo: "Ciclo de escritura",
            help_font: "Cambiar Fuente",
            help_files: "Abrir Archivos",
            help_nav: "Abrir Estructura",
            help_memo: "Abrir Memos",
            help_drawer_close: "Cerrar Cajón",
            help_slash_hint: "Escriba en el editor para activar:",
            help_save_short: "Guardar",
            help_open_short: "Importar",
            help_theme_short: "Cambiar Tema",
            help_fullscreen_short: "Pantalla Completa",
            help_music_short: "Música",
            help_pomo_short: "Ciclo de escritura",
            tab_files: "Archivos [Alt+1]",
            tab_nav: "Estructura [Alt+2]",
            tab_memo: "Memos [Alt+3]",
            tab_theme: "Tema [Alt+T]",
            tab_books: "TΦTBooks [Alt+4]",
            hard_reset_title: "HARD RESET",
            fullscreen_title: "Pantalla Completa [F11]",
            drawer_system: "SISTEMA",
            drawer_actions: "ACCIONES",
            drawer_search: "BÚSQUEDA",
            drawer_files: "ARCHIVOS",
            drawer_nav: "ESTRUCTURA",
            drawer_memo: "MEMOS",
            btn_new_project: "+ NUEVO",
            btn_import_title: "Importar JSON/TXT",
            btn_open: "ABRIR",
            btn_scan_qr: "Scan QR",
            btn_scan: "SCAN QR",
            nav_structure: "Estructura del documento:",
            nav_insert: "INSERTAR MARCADOR",
            nav_empty_hint: "Usa \"Insertar marcador\" para navegar.",
            nav_delete_confirm: "Borrar marcador",
            memo_ph: "Nota rápida...",
            files_hint: "Controla archivos y copias localmente.",
            nav_hint: "Ve la estructura del texto y navega con marcadores.",
            memo_hint: "Notas y fragmentos externos. No genera autoría.",
            mobile_theme: "CAMBIAR TEMA",
            mobile_full_enable: "ACTIVAR MODO COMPLETO",
            mobile_full_disable: "VOLVER A MEMO",
            mobile_memo_ph: "Nota rápida...",
            mobile_memo_tags: "Tags (separa por coma)",
            mobile_memo_add: "GUARDAR MEMO",
            mobile_memo_delete: "BORRAR",
            mobile_export_memos: "EXPORTAR MEMOS",
            mobile_intro_title: "MODO MÓVIL",
            mobile_intro_body: "<p>Disponible offline después del primer acceso.</p><p>El móvil se reduce a lo esencial: scanner QR y notas rápidas.</p><p>Desliza hacia arriba para ocultar el scanner y escribir en memo.</p><p>Exporta JSON e importa en desktop para el proyecto completo.</p>",
            mobile_intro_ok: "ENTENDI",
            offline_download: "DESCARGAR APP OFFLINE",
            project_github: "GITHUB DEL PROYECTO",
            qr_stream_title: "STREAM QR",
            qr_stream_active: "STREAM ACTIVO",
            qr_stream_pause: "PAUSAR",
            qr_stream_hint: "Cierre para terminar el envío.",
            qr_stream_instructions: "<p>1) En el celular, abre TΦT y ve a Archivos → Scan QR.</p><p>2) Apunta a esta pantalla hasta completar.</p><p>3) Luego borra todo aquí.</p>",
            qr_scan_title: "SCAN QR",
            qr_scan_wait: "ESPERANDO QR...",
            qr_scan_stop: "DETENER SCAN",
            qr_fallback_hint: "Sin camara? Importa el archivo .b64 o pega la cadena.",
            qr_fallback_import: "IMPORTAR ARCHIVO",
            qr_fallback_paste: "Pega la cadena base64",
            qr_fallback_restore: "RESTAURAR",
            reader_glossary: "GLOSARIO",
            lexicon_title: "DICCIONARIO",
            lexicon_trans: "TRADUCCIONES",
            inline_data_title: "DATOS",
            inline_data_words: "Palabras",
            inline_data_chars: "Caracteres",
            inline_data_keys: "Pulsaciones",
            inline_data_cert: "Certificado",
            inline_data_session: "Sesión",
            inline_dice_title: "DADO",
            goal_label: "META",
            goal_done_title: "META CUMPLIDA",
            goal_done_body: "Felicidades, alcanzaste tu meta de escritura.",
            goal_500_title: "500 PALABRAS",
            goal_500_body: "Bien. Sigue hasta 1000 palabras.",
            goal_1000_title: "1000 PALABRAS",
            goal_1000_body: "Buen ritmo. Ve por 1500.",
            goal_1500_title: "1500 PALABRAS",
            goal_1500_body: "Casi listo. Apunta a 2000.",
            goal_2000_title: "2000 PALABRAS",
            goal_2000_body: "Excelente. Meta máxima lograda.",
            reader_glossary_title: "Glosario",
            reader_ruler_title: "Regla",
            reader_font_title: "Fuente",
            reader_theme_title: "Tema",
            reader_play_title: "Play",
            reader_close_title: "Cerrar",
            default_project: "Borrador Inicial",
            alert_backup_restored: "✅ BACKUP RESTAURADO CON ÉXITO!",
            alert_backup_invalid: "Error: Backup inválido o corrupto.",
            alert_capsule_restored: "✅ CÁPSULA TΦT RESTAURADA CON ÉXITO!",
            alert_capsule_invalid: "Error: Cápsula inválida o corrupta.",
            print_popup_blocked: "El navegador bloqueó la pestaña de impresión. Permite pop-ups para continuar.",
            alert_backup_json_error: "Error al leer el archivo JSON.",
            prompt_file_name: "Nombre del Archivo:",
            reset_no_text: "SIN TEXTO PARA VALIDAR. CONTINÚE AL PASO 2.",
            reset_proof_ok: "VERIFICACIÓN OK.",
            reset_proof_fail: "PALABRA INCORRECTA.",
            reset_executing: "EJECUTANDO PROTOCOLO...",
            reset_denied: "CONTRASEÑA INCORRECTA. ACCESO DENEGADO.",
            pomo_unlocked: "ACCESO LIBERADO.",
            pomo_wrong_pass: "CONTRASEÑA INCORRECTA.",
            pomo_break_label: "PAUSA",
            qr_stream_paused: "STREAM PAUSADO",
            qr_stream_resume: "REANUDAR",
            qr_stream_empty: "SIN DATOS PARA STREAM.",
            qr_libs_missing: "El paquete QR aún no cargó. Inténtalo de nuevo.",
            qr_no_detector: "BarcodeDetector no disponible. Use importación por archivo.",
            qr_using_fallback: "Decoder offline activo. Apunte la cámara.",
            qr_camera_missing: "Elemento de cámara ausente.",
            qr_camera_blocked: "CÁMARA BLOQUEADA O NO DISPONIBLE.",
            qr_receiving: "RECIBIENDO",
            qr_restore_in_progress: "BACKUP COMPLETO. RESTAURANDO...",
            qr_decode_fail: "FALLO EN LA DECODIFICACIÓN."
            ,
            qr_frame: "FRAME"
            ,
            confirm_exit: "¿Desea cerrar el sistema?"
            ,
            chapter_title: "NUEVO CAPÍTULO",
            chapter_placeholder: "..."
        },
        fr: {
            lang_label: "FRAN",
            lang_title: "Langue",
            manifesto_title: "TΦT — Type over Tap",
            manifesto_subtitle: "Écriture privée à l’ère de l’IA.",
            manifesto_body: "<div class=\"manifesto-top\"><h2>C’est une scène vide.</h2><p>Vous installez votre table. Puis vous écrivez hors réseau.</p></div><div class=\"manifesto-lines\"><p>Vous écrivez localement. Rien ne dépend d’internet. Rien ne se perd.</p><p>Le mobile conserve et transporte. Les idées deviennent des notes.</p><p>Exporter et effacer font partie du rituel.</p></div><div class=\"manifesto-tech\"><p>Le système enregistre le geste humain : temps, rythme, séquence.</p><p>Sans profils. Sans cloud. Sans télémétrie.</p></div>",
            manifesto_accept: "J'AI LU ET COMPRIS",
            manifesto_pomo_hint: "Choisissez votre premier cycle de travail.",
            terms_link: "Termos de uso",
            terms_accept_hint: "Ao iniciar uma sessão, você aceita os Termos de uso.",
            terms_title: "Utilisation responsable de TΦT",
            terms_body: "<p>TΦT est un outil expérimental créé par un écrivain pour aider d’autres écrivains à travailler avec plus de confidentialité et de concentration.</p><p>En utilisant ce système, vous comprenez et acceptez que :</p><ul><li>TΦT est fourni « tel quel », sans garantie expresse ou implicite.</li><li>Des défaillances peuvent survenir, y compris des bugs logiciels, pertes de données, corruptions de fichiers, problèmes de navigateur, de matériel ou de système d’exploitation, coupures de courant, blocages, erreurs d’utilisation ou limitations de l’environnement local.</li><li>Bien que le système ait été largement testé, aucun logiciel n’est infaillible.</li><li>La responsabilité de l’exportation, de la sauvegarde, du stockage et de la protection de vos textes incombe exclusivement à l’utilisateur.</li></ul><p>TΦT ne garantit pas l’auteur légal, l’enregistrement officiel, la validité juridique ni la protection absolue d’un texte. Les hashages, métadonnées et enregistrements techniques peuvent constituer une preuve mathématique d’antériorité, mais ne remplacent pas un enregistrement légal formel.</p><p>L’auteur de TΦT décline toute responsabilité en cas de pertes, dommages directs ou indirects, manque à gagner, interruptions, usage abusif du système, revendications d’auteur ou attentes non satisfaites.</p><p>En acceptant ces conditions, vous reconnaissez que :</p><ul><li>vous utilisez un outil indépendant,</li><li>conçu comme une expérience technique et culturelle,</li><li>sans support formel ni garantie de service,</li><li>et que vous assumez l’entière responsabilité de son utilisation.</li></ul><p>Si vous comprenez et acceptez ces conditions, vous pouvez commencer.</p>",
            terms_check: "J’ai lu, compris et accepté les conditions d’utilisation",
            terms_primary: "Accepter et commencer",
            terms_back: "Voltar",
            terms_tip: "Dica: exporte com frequência e guarde seus backups.",
            terms_close: "Fechar",
            verify_link: "Vérifier un fichier .tot",
            welcome: "DÉMARRAGE DU SYSTÈME",
            create_pass: "Créer un mot de passe de session",
            repeat_pass: "CONFIRMER LE MOT DE PASSE",
            setup_project_label: "Nom du projet",
            start_btn: "Créer la session locale",
            locked: "SYSTÈME VERROUILLÉ",
            unlock_btn: "DÉVERROUILLER",
            wrong_pass: "MOT DE PASSE INCORRECT",
            reset_warn: "DANGER : TOUT SERA EFFACÉ. CONTINUER ?",
            reset_invalid: "MOTS DE PASSE INVALIDES OU DIFFÉRENTS.",
            reset_cancel: "MOT DE PASSE INCORRECT. OPÉRATION ANNULÉE.",
            reset_prompt: "ENTREZ LE MOT DE PASSE POUR CONFIRMER L'EFFACEMENT :",
            modal_title: "CONFIRMATION",
            modal_ok: "OK",
            modal_cancel: "ANNULER",
            project_delete_confirm: "Supprimer le fichier",
            stats_chars: "CHARS",
            stats_words: "WORDS",
            stats_label: "CHARS: 0 | WORDS: 0",
            marquee_ready: "/// SYSTÈME PRÊT /// APPUYEZ SUR [F1] POUR L'AIDE :: TAPEZ --H DANS L'ÉDITEUR",
            editor_placeholder: "Écrivez ici. Ce texte naît avec une paternité enregistrée.",
            font_title: "Changer la police [Alt+F]",
            font_mode_neutral: "Neutre",
            font_mode_literary: "Littéraire",
            font_mode_author: "Auteur",
            font_minus_title: "Réduire la police",
            font_plus_title: "Agrandir la police",
            save_title: "Enregistrer [Ctrl+S]",
            export_btn: "EXPORTER",
            search_ph: "Rechercher...",
            search_tip: "Rechercher [Ctrl+F]",
            search_go: "OK",
            search_prev_title: "Précédent",
            search_next_title: "Suivant",
            paste_blocked: "Le collage n'est pas autorisé dans ce champ.\nUtilisez Mémo pour le contenu externe.",
            search_clear_title: "Effacer la recherche",
            audio_title: "Musique [Alt+M]",
            audio_btn: "SON",
            reader_title: "Mode Lecture",
            reader_btn: "LECTEUR",
            reader_ruler_close_title: "Fermer la règle",
            xray_title: "RASTRO",
            xray_btn: "RASTRO",
            verify_title: "TΦT Verify",
            verify_tip: "Vérifier un fichier .tot",
            xray_tooltip: "Disponível em português do Brasil",
            xray_locked_intl: "RASTRO est actuellement disponible uniquement en portugais du Brésil.",
            consult_title: "Consulter",
            consult_close_title: "Fermer",
            consult_button: "CONSULTER",
            consult_pos: "Classe",
            consult_def: "Définition",
            consult_flex: "Flexions",
            consult_regency: "Régence",
            consult_examples: "Exemples",
            consult_notes: "Notes",
            consult_doubt: "Doute courant",
            consult_not_found: "Mot introuvable dans le dictionnaire hors ligne.",
            consult_amb_note: "L'usage dépend du contexte ; lecture ambiguë.",
            consult_out_scope: "Hors du périmètre du dictionnaire hors ligne (pour l'instant).",
            consult_add_personal: "Accepter comme terme de l’auteur",
            consult_status_idle: "—",
            consult_status_tried: "Essais :",
            consult_status_added: "Ajouté au dictionnaire personnel.",
            consult_class_unknown: "indéterminée (hors ligne)",
            consult_class_probable: "probable",
            consult_class_context: "contexte",
            consult_fallback_title: "Observations dans le texte",
            consult_fallback_class: "Classe",
            consult_fallback_form: "Forme",
            consult_fallback_count: "Occurrences dans le texte",
            consult_fallback_para: "Occurrences dans le paragraphe",
            consult_fallback_repeat: "Répétition proche",
            consult_fallback_singular: "Singulier",
            consult_fallback_plural: "Pluriel",
            consult_fallback_yes: "Oui",
            consult_fallback_no: "Non",
            xray_panel_title: "RAYON-X DU TEXTE",
            xray_help_title: "Aide",
            xray_help_tip: "Aide",
            xray_drag_title: "Déplacer",
            xray_drag_tip: "Faire glisser la fenêtre",
            xray_close_title: "Fermer",
            xray_close_tip: "Fermer",
            xray_verbs_title: "VERBES",
            xray_adjs_title: "ADJECTIFS",
            xray_tab_verbs: "Verbes",
            xray_tab_adjs: "Adjectifs",
            xray_tab_review: "Réviser",
            xray_tip_lex: "Lexique validé.",
            xray_tip_heur: "Heuristique sans validation.",
            xray_tip_amb: "Forme ambiguë (plus d’une lecture).",
            xray_tip_high: "Confiance élevée (lexique).",
            xray_tip_med: "Confiance moyenne (consensus partiel).",
            xray_tip_low: "Confiance faible (heuristique).",
            xray_tip_uncertain: "Lemme incertain (sans validation).",
            xray_search_ph: "Chercher lemme ou forme...",
            xray_sort_count: "Occurrences",
            xray_sort_alpha: "A-Z",
            xray_sort_conf: "Confiance",
            xray_filter_amb_only: "Ambigus uniquement",
            xray_label_verbs: "Verbes",
            xray_label_adjs: "Adjectifs",
            xray_label_occurrences: "occurrences",
            xray_label_lemmas: "lemmes",
            xray_label_amb: "Ambigus",
            xray_badge_verb: "VERBE",
            xray_badge_adj: "ADJ",
            xray_badge_alert: "ALERTE",
            xray_lemma_tooltip: "LEMME est la forme de base pour regrouper les variations. Ex. : aime, aimer, aimerai → aimer.",
            xray_lemma_unknown: "LEMME INCERTAIN",
            xray_lemma_unknown_badge: "INCERTAIN",
            xray_part_reason_aux: "Auxiliaire fort avant le participe.",
            xray_part_reason_aux_weak: "Auxiliaire d'état avant le participe.",
            xray_part_reason_passive: "Voix passive possible (par...).",
            xray_part_reason_intensifier: "Intensifieur typique d'adjectif.",
            xray_part_reason_noun: "Après un nom avec déterminant.",
            xray_part_reason_coord: "Coordonné avec un adjectif.",
            xray_part_reason_amb: "Contexte insuffisant pour trancher.",
            xray_part_alternatives: "Analyses possibles",
            xray_alert_tag: "ALERTE",
            xray_alert_doubt: "Doute",
            xray_alert_regency: "Régence",
            xray_alert_style_adj: "Répétition d'adjectif",
            xray_alert_style_tense: "Verbes au même temps",
            xray_alert_style_serestar: "Usage excessif de ser/estar",
            xray_alert_paragraph: "paragraphe",
            xray_alert_occurrences: "occurrences",
            xray_legend_lex: "LÉX",
            xray_legend_heur: "HEUR",
            xray_legend_amb: "AMB",
            xray_legend_high: "ÉLEVÉE",
            xray_legend_med: "MOYENNE",
            xray_legend_low: "FAIBLE",
            xray_help_heading: "Légende",
            xray_help_body: "<p><strong>LEMME</strong> est la forme de base (ex. : aimer). <strong>FORME</strong> est ce qui apparaît dans le texte.</p><p><strong>TAG</strong> indique forme/temps : INF, GER, PART, PRES, FUT, IMP, COND.</p><p><strong>ÉLEVÉE</strong> = lexique. <strong>MOYENNE</strong> = consensus partiel. <strong>FAIBLE</strong> = heuristique.</p><p><strong>AMB</strong> = forme ambiguë (plus d'une classe).</p>",
            xray_empty: "Données insuffisantes.",
            xray_policy: "Regroupé par lemme. Compte les verbes (infinitif/gérondif/participe) et les adjectifs. Les éléments ambigus sont signalés.",
            xray_lexicon_status: "Pack linguistique",
            xray_audit_toggle: "Auditer",
            xray_conf_high: "élevée",
            xray_conf_med: "moyenne",
            xray_conf_low: "faible",
            lock_title: "Verrouiller l'écran [Alt+L]",
            lock_btn: "LOCK",
            export_title: "PROTOCOLE D'EXPORT",
            export_markdown: "EXPORTER MARKDOWN",
            export_json: "EXPORTER LA CAPSULE",
            export_capsule_tip: "Fichier vérifiable d’écriture humaine créé dans TΦT.",
            export_report_full: "IMPRESSION COMPLETE",
            export_qr_stream: "STREAM QR",
            export_note: "Contient le texte et la preuve technique du processus d’écriture.",
            export_social_title: "RÉSEAUX FÉDÉRÉS",
            export_social_bigtech: "RÉSEAUX NON FÉDÉRÉS (SANS CONTRÔLE RÉEL DU CONTENU)",
            share_title: "PARTAGER TΦT",
            share_copy: "COPIER LE TEXTE",
            share_open: "OUVRIR LE RÉSEAU",
            share_message: "J'écris dans 🔸 TΦT Writer. Écrit, exporté, effacé. Un bunker hors ligne pour écrire en privé. https://tot.undo.it/",
            fediverse_help: "VOUS NE SAVEZ PAS CE QU'EST LE FEDIVERSE?",
            fediverse_title: "FEDIVERSE",
            fediverse_body: "<p>Pensez aux réseaux sociaux comme aux emails : vous choisissez un fournisseur et vous parlez à tout le monde. Le fediverse fonctionne pareil.</p><p>Au lieu d'une entreprise qui contrôle tout, plusieurs communautés se connectent. Vous choisissez où être, gardez vos données et restez connecté.</p><p>Moins de surveillance, plus de contrôle, plus de liberté.</p>",
            export_active: "actif",
            export_all: "tout",
            export_light: "lumière",
            danger_zone: "ZONE DE DANGER",
            reset_warn_body: "Cela supprimera TOUS les fichiers et réglages.",
            reset_proof: "VÉRIFICATION DU CONTENU : TAPEZ UN MOT DU TEXTE",
            reset_keyword: "Mot du texte",
            reset_validate: "Vérifier le contenu",
            reset_confirm: "OUI, SUPPRIMER",
            reset_password_prompt: "ENTREZ LE MOT DE PASSE DE SESSION POUR AUTORISER LA DESTRUCTION :",
            reset_password_ph: "Mot de passe de session",
            reset_destroy: "Détruire la session locale",
            pomo_locked: "CYCLE D'ÉCRITURE ACTIF",
            pomo_break: "PAUSE ACTIVE",
            pomo_break_hint: "Le déverrouillage nécessite le mot de passe de session.",
            pomo_unlock_prompt: "ENTREZ LE MOT DE PASSE DE SESSION POUR DÉVERROUILLER :",
            pomo_choice: "CHOISISSEZ LE PROCHAIN BLOC :",
            pomo_25: "25 MIN",
            pomo_55: "50 MIN",
            pomo_btn: "POMODORO",
            pomo_tip: "Cycle de focus",
            help_title: "MANUEL DE COMMANDE",
            help_tab_general: "GÉNÉRAL",
            help_tab_tools: "OUTILS",
            help_tab_nav: "STRUCTURE",
            help_tab_slash: "SLASH COMMANDS",
            help_help: "Aide",
            help_save: "Enregistrer / Exporter",
            help_open: "Ouvrir / Importer",
            help_fullscreen: "Plein écran (Zen)",
            help_search: "Rechercher",
            help_close: "Fermer / Focus Éditeur",
            help_theme: "Changer Thème",
            help_music: "Musique (Play / Stop)",
            help_pomo: "Cycle d'écriture",
            help_font: "Changer Police",
            help_files: "Ouvrir Fichiers",
            help_nav: "Ouvrir Structure",
            help_memo: "Ouvrir Mémos",
            help_drawer_close: "Fermer le tiroir",
            help_slash_hint: "Tapez dans l'éditeur pour activer :",
            help_save_short: "Enregistrer",
            help_open_short: "Importer",
            help_theme_short: "Changer Thème",
            help_fullscreen_short: "Plein écran",
            help_music_short: "Musique",
            help_pomo_short: "Cycle d'écriture",
            tab_files: "Fichiers [Alt+1]",
            tab_nav: "Structure [Alt+2]",
            tab_memo: "Mémos [Alt+3]",
            tab_theme: "Thème [Alt+T]",
            tab_books: "TΦTBooks [Alt+4]",
            hard_reset_title: "HARD RESET",
            fullscreen_title: "Plein écran [F11]",
            drawer_system: "SYSTÈME",
            drawer_actions: "ACTIONS",
            drawer_search: "RECHERCHE",
            drawer_files: "FICHIERS",
            drawer_nav: "NAVIGATION",
            drawer_memo: "MÉMOS",
            btn_new_project: "+ NOUVEAU",
            btn_import_title: "Importer JSON/TXT",
            btn_open: "OUVRIR",
            btn_scan_qr: "Scan QR",
            btn_scan: "SCAN QR",
            nav_structure: "Structure du document :",
            nav_insert: "INSÉRER MARQUEUR",
            nav_empty_hint: "Utilisez \"Insérer marqueur\" pour naviguer.",
            nav_delete_confirm: "Supprimer le marqueur",
            memo_ph: "Note rapide…",
            files_hint: "Gérez vos fichiers et sauvegardes localement.",
            nav_hint: "Voyez la structure du texte et naviguez avec des marqueurs.",
            memo_hint: "Notes et extraits externes. Pas d’auteur enregistré.",
            mobile_theme: "CHANGER THÈME",
            mobile_full_enable: "ACTIVER MODE COMPLET",
            mobile_full_disable: "RETOUR AU MÉMO",
            mobile_memo_ph: "Note rapide…",
            mobile_memo_tags: "Tags (séparés par virgule)",
            mobile_memo_add: "ENREGISTRER",
            mobile_memo_delete: "SUPPRIMER",
            mobile_export_memos: "EXPORTER MÉMOS",
            mobile_intro_title: "MODE MOBILE",
            mobile_intro_body: "<p>Disponible hors ligne après le premier accès.</p><p>Le mobile est réduit à l'essentiel : scanner QR et notes rapides.</p><p>Glissez vers le haut pour masquer le scanner et écrire en mémo.</p><p>Exportez JSON et importez sur desktop pour le projet complet.</p>",
            mobile_intro_ok: "COMPRIS",
            offline_download: "TÉLÉCHARGER L'APP OFFLINE",
            project_github: "GITHUB DU PROJET",
            qr_stream_title: "STREAM QR",
            qr_stream_active: "STREAM ACTIF",
            qr_stream_pause: "PAUSE",
            qr_stream_hint: "Fermez pour terminer l'envoi.",
            qr_stream_instructions: "<p>1) Sur votre téléphone, ouvrez TΦT puis Fichiers → Scan QR.</p><p>2) Visez cet écran jusqu'à la fin.</p><p>3) Ensuite, effacez tout ici.</p>",
            qr_scan_title: "SCAN QR",
            qr_scan_wait: "EN ATTENTE DU QR...",
            qr_scan_stop: "ARRÊTER SCAN",
            qr_fallback_hint: "Sans caméra ? Importez le fichier .b64 ou collez la chaîne.",
            qr_fallback_import: "IMPORTER FICHIER",
            qr_fallback_paste: "Collez la chaîne base64",
            qr_fallback_restore: "RESTAURER",
            reader_glossary: "GLOSSAIRE",
            lexicon_title: "DICTIONNAIRE",
            lexicon_trans: "TRADUCTIONS",
            inline_data_title: "DONNÉES",
            inline_data_words: "Mots",
            inline_data_chars: "Caractères",
            inline_data_keys: "Frappes",
            inline_data_cert: "Certificat",
            inline_data_session: "Session",
            inline_dice_title: "DÉ",
            goal_label: "OBJECTIF",
            goal_done_title: "OBJECTIF ATTEINT",
            goal_done_body: "Bravo, vous avez atteint votre objectif d'écriture.",
            goal_500_title: "500 MOTS",
            goal_500_body: "Bien. Continuez jusqu'à 1000 mots.",
            goal_1000_title: "1000 MOTS",
            goal_1000_body: "Bon rythme. Visez 1500.",
            goal_1500_title: "1500 MOTS",
            goal_1500_body: "Presque. Atteignez 2000.",
            goal_2000_title: "2000 MOTS",
            goal_2000_body: "Excellent. Objectif maximal atteint.",
            reader_glossary_title: "Glossaire",
            reader_ruler_title: "Règle",
            reader_font_title: "Police",
            reader_theme_title: "Thème",
            reader_play_title: "Play",
            reader_close_title: "Fermer",
            default_project: "Brouillon Initial",
            alert_backup_restored: "✅ SAUVEGARDE RESTAURÉE AVEC SUCCÈS !",
            alert_backup_invalid: "Erreur : sauvegarde invalide ou corrompue.",
            alert_capsule_restored: "✅ CAPSULE TΦT RESTAURÉE AVEC SUCCÈS !",
            alert_capsule_invalid: "Erreur : capsule invalide ou corrompue.",
            print_popup_blocked: "Votre navigateur a bloqué l’onglet d’impression. Autorisez les pop-ups pour continuer.",
            alert_backup_json_error: "Erreur de lecture du fichier JSON.",
            prompt_file_name: "Nom du fichier :",
            reset_no_text: "AUCUN TEXTE À VALIDER. CONTINUEZ À L'ÉTAPE 2.",
            reset_proof_ok: "VÉRIFICATION OK.",
            reset_proof_fail: "MOT INCORRECT.",
            reset_executing: "EXÉCUTION DU PROTOCOLE...",
            reset_denied: "MOT DE PASSE INCORRECT. ACCÈS REFUSÉ.",
            pomo_unlocked: "ACCÈS AUTORISÉ.",
            pomo_wrong_pass: "MOT DE PASSE INCORRECT.",
            pomo_break_label: "PAUSE",
            qr_stream_paused: "STREAM EN PAUSE",
            qr_stream_resume: "REPRENDRE",
            qr_stream_empty: "AUCUNE DONNÉE À STREAMER.",
            qr_libs_missing: "Le pack QR n’est pas encore chargé. Réessayez.",
            qr_no_detector: "BarcodeDetector indisponible. Utilisez l'import de fichier.",
            qr_using_fallback: "Décodage hors ligne actif. Pointez la caméra.",
            qr_camera_missing: "Élément caméra manquant.",
            qr_camera_blocked: "CAMÉRA BLOQUÉE OU INDISPONIBLE.",
            qr_receiving: "RÉCEPTION",
            qr_restore_in_progress: "SAUVEGARDE COMPLÈTE. RESTAURATION...",
            qr_decode_fail: "ÉCHEC DU DÉCODAGE."
            ,
            qr_frame: "FRAME"
            ,
            confirm_exit: "Voulez-vous fermer le système ?"
            ,
            chapter_title: "NOUVEAU CHAPITRE",
            chapter_placeholder: "..."
        }
    },
    init() {
        const saved = localStorage.getItem('lit_lang') || 'pt';
        this.setLang(saved);
    },
    t(key) {
        const t = this.db[this.current] || {};
        return t[key] || key;
    },
    setLang(l) {
        this.current = l;
        localStorage.setItem('lit_lang', l);
        this.apply();
    },
    cycleLang() {
        const index = this.languages.findIndex((l) => l.code === this.current);
        const next = this.languages[(index + 1 + this.languages.length) % this.languages.length];
        this.setLang(next.code);
    },
    apply() {
        const t = this.db[this.current];
        const xray = this.db.pt || {};
        const getText = (key) => {
            if (key && key.startsWith("xray_") && !key.startsWith("xray_locked")) {
                return xray[key] || t[key];
            }
            return t[key];
        };
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            const val = getText(key);
            if (val) el.innerText = val;
        });
        document.querySelectorAll('[data-i18n-html]').forEach(el => {
            const key = el.getAttribute('data-i18n-html');
            const val = getText(key);
            if (val) el.innerHTML = val;
        });
        document.querySelectorAll('[data-i18n-title]').forEach(el => {
            const key = el.getAttribute('data-i18n-title');
            const val = getText(key);
            if (val) {
                el.setAttribute('aria-label', val);
                el.removeAttribute('title');
            }
        });
        document.querySelectorAll('[data-i18n-tip]').forEach(el => {
            const key = el.getAttribute('data-i18n-tip');
            const val = getText(key);
            if (val) {
                el.setAttribute('data-tip', val);
            } else {
                el.removeAttribute('data-tip');
            }
            el.removeAttribute('title');
        });
        document.querySelectorAll('[title]').forEach(el => {
            const title = el.getAttribute('title');
            if (title && !el.getAttribute('aria-label')) {
                el.setAttribute('aria-label', title);
            }
            el.removeAttribute('title');
        });
        document.querySelectorAll('input[data-i18n-ph], textarea[data-i18n-ph]').forEach(el => {
            const key = el.getAttribute('data-i18n-ph');
            const val = getText(key);
            if (val) el.placeholder = val;
        });
        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            const val = getText(key);
            if (val) el.setAttribute('data-placeholder', val);
        });
        document.querySelectorAll('[data-i18n-lang]').forEach(el => {
            if (t.lang_label) el.innerText = t.lang_label;
        });
        const langButtons = [document.getElementById("btnLangToggle"), document.getElementById("setupLangToggle")];
        langButtons.forEach((btn) => {
            if (btn && t.lang_label) btn.innerText = t.lang_label;
        });
        document.dispatchEvent(new CustomEvent("lang:changed", { detail: { code: this.current } }));
    }
};
