export const xrayTests = [
  { type: "verb", form: "amo", lemma: "amar", tag: "PRES/1S" },
  { type: "verb", form: "amar", lemma: "amar", tag: "INF" },
  { type: "verb", form: "amarei", lemma: "amar", tag: "FUT/1S" },
  { type: "verb", form: "sou", lemma: "ser", tag: "PRES/1S" },
  { type: "verb", form: "foi", lemma: "ser/ir", tag: "PRET/3S" },
  { type: "verb", form: "estou", lemma: "estar", tag: "PRES/1S" },
  { type: "verb", form: "tenho", lemma: "ter", tag: "PRES/1S" },
  { type: "verb", form: "vou", lemma: "ir", tag: "PRES/1S" },
  { type: "verb", form: "falo", lemma: "falar", tag: "PRES/1S" },
  { type: "verb", form: "escrevo", lemma: "escrever", tag: "PRES/1S" },
  { type: "verb", form: "leio", lemma: "ler", tag: "PRES/1S" },
  { type: "verb", form: "chego", lemma: "chegar", tag: "PRES/1S" },
  { type: "verb", form: "trago", lemma: "trazer", tag: "PRES/1S" },
  { type: "verb", form: "abro", lemma: "abrir", tag: "PRES/1S" },
  { type: "verb", form: "fecho", lemma: "fechar", tag: "PRES/1S" },
  { type: "verb", form: "crio", lemma: "criar", tag: "PRES/1S" },
  { type: "verb", form: "guardo", lemma: "guardar", tag: "PRES/1S" },
  { type: "verb", form: "ando", lemma: "andar", tag: "PRES/1S" },
  { type: "verb", form: "fico", lemma: "ficar", tag: "PRES/1S" },
  { type: "verb", form: "espero", lemma: "esperar", tag: "PRES/1S" },
  { type: "verb", form: "preciso", lemma: "precisar", tag: "PRES/1S" },
  { type: "verb", form: "imagino", lemma: "imaginar", tag: "PRES/1S" },
  { type: "verb", form: "lembro", lemma: "lembrar", tag: "PRES/1S" },
  { type: "verb", form: "chamo", lemma: "chamar", tag: "PRES/1S" },
  { type: "verb", form: "canto", lemma: "cantar", tag: "PRES/1S" },
  { type: "verb", form: "choro", lemma: "chorar", tag: "PRES/1S" },
  { type: "verb", form: "caminho", lemma: "caminhar", tag: "PRES/1S" },
  { type: "verb", form: "moro", lemma: "morar", tag: "PRES/1S" },
  { type: "verb", form: "uso", lemma: "usar", tag: "PRES/1S" },
  { type: "verb", form: "sigo", lemma: "seguir", tag: "PRES/1S" },
  { type: "verb", form: "creio", lemma: "crer", tag: "PRES/1S" },
  { type: "verb", form: "dir-se-a", lemma: "dizer", tag: "FUT/3S", ambiguous: true },
  { type: "verb", form: "amar-te-ei", lemma: "amar", tag: "FUT/1S", ambiguous: true },
  { type: "verb", form: "mando", lemma: "mandar", tag: "PRES/1S" },
  { type: "verb", form: "deixo", lemma: "deixar", tag: "PRES/1S" },
  { type: "verb", form: "devo", lemma: "dever", tag: "PRES/1S" },
  { type: "verb", form: "levo", lemma: "levar", tag: "PRES/1S" },
  { type: "verb", form: "trabalho", lemma: "trabalhar", tag: "PRES/1S" },
  { type: "verb", form: "olho", lemma: "olhar", tag: "PRES/1S" },
  { type: "verb", form: "perco", lemma: "perder", tag: "PRES/1S" },
  { type: "verb", form: "ajudo", lemma: "ajudar", tag: "PRES/1S" },
  { type: "verb", form: "toco", lemma: "tocar", tag: "PRES/1S" },
  { type: "verb", form: "tento", lemma: "tentar", tag: "PRES/1S" },
  { type: "adj", form: "bonito", lemma: "bonito", tag: "MASC.SG" },
  { type: "adj", form: "bonitas", lemma: "bonito", tag: "FEM.PL" },
  { type: "adj", form: "cansado", lemma: "cansado", tag: "MASC.SG" },
  { type: "adj", form: "feliz", lemma: "feliz", tag: "INVAR" },
  { type: "adj", form: "triste", lemma: "triste", tag: "INVAR" },
  { type: "adj", form: "menor", lemma: "pequeno", tag: "COMP" },
  { type: "adj", form: "lindo", lemma: "lindo", tag: "MASC.SG" },
  { type: "adj", form: "necessario", lemma: "necessario", tag: "MASC.SG" },
  { type: "adj", form: "pesado", lemma: "pesado", tag: "MASC.SG" },
  { type: "adj", form: "meio", lemma: "meio", tag: "INVAR", ambiguous: true },
  { type: "adj", form: "muito", lemma: "muito", tag: "INVAR", ambiguous: true },
  { type: "adj", form: "mesmo", lemma: "mesmo", tag: "MASC.SG", ambiguous: true },
  { type: "adj", form: "pode", lemma: "poder", tag: "PRES/3S", ambiguous: true },
  { type: "adj", form: "melhor", lemma: "bom", tag: "COMP", ambiguous: true },
  { type: "adj", form: "pior", lemma: "mau", tag: "COMP", ambiguous: true },
  { type: "adj", form: "maior", lemma: "grande", tag: "COMP", ambiguous: true },
  { type: "adj", form: "fraco", lemma: "fraco", tag: "MASC.SG" },
  { type: "adj", form: "forte", lemma: "forte", tag: "INVAR" },
  { type: "adj", form: "puro", lemma: "puro", tag: "MASC.SG" },
  { type: "adj", form: "pouco", lemma: "pouco", tag: "MASC.SG", ambiguous: true },
  { type: "adj", form: "mesmo", lemma: "mesmo", tag: "MASC.SG", ambiguous: true },
  { type: "adj", form: "claro", lemma: "claro", tag: "MASC.SG", ambiguous: true }
];
